name: Playwright QA

on: [push, workflow_dispatch]

jobs:
  qa:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install playwright

    - name: Run Playwright script (email: 23f1000267@ds.study.iitm.ac.in)
      run: node scrape.js
